export const ENGINE_ACTIONS = Object.freeze({
  INICIAR_PARTIDA: "iniciarPartida",
  TIRAR_DADOS: "tirarDados",
  COMPRAR_PROPIEDAD: "comprarPropiedad",
  RECHAZAR_COMPRA: "rechazarCompra",
  INICIAR_SUBASTA: "iniciarSubasta",
  HACER_OFERTA: "hacerOferta",
  RETIRARSE_DE_SUBASTA: "retirarseDeSubasta",
  RESOLVER_CARTA: "resolverCarta",
  PAGAR_RENTA: "pagarRenta",
  PAGAR_IMPUESTO: "pagarImpuesto",
  COMPRAR_CASA: "comprarCasa",
  COMPRAR_HOTEL: "comprarHotel",
  VENDER_CASA: "venderCasa",
  VENDER_HOTEL: "venderHotel",
  HIPOTECAR_PROPIEDAD: "hipotecarPropiedad",
  LEVANTAR_HIPOTECA: "levantarHipoteca",
  VENDER_PROPIEDAD: "venderPropiedad",
  COMPRAR_CARTA_SALIR_CARCEL: "comprarCartaSalirCarcel",
  USAR_CARTA_SALIR_CARCEL: "usarCartaSalirCarcel",
  PAGAR_MULTA_CARCEL: "pagarMultaCarcel",
  RESOLVER_DEUDA_PENDIENTE: "resolverDeudaPendiente",
  RESOLVER_QUIEBRA: "resolverQuiebra",
  TERMINAR_TURNO: "terminarTurno"
});
