export const GAME_MODES = Object.freeze({
  NORMAL: "NORMAL",
  SHORT: "SHORT",
  TIMED: "TIMED"
});

export const GAME_STATUSES = Object.freeze({
  PREPARACION: "PREPARACION",
  JUGANDO: "JUGANDO",
  ESPERANDO_ACCION_DEL_JUGADOR: "ESPERANDO_ACCION_DEL_JUGADOR",
  RESOLVIENDO_CASILLA: "RESOLVIENDO_CASILLA",
  SUBASTA: "SUBASTA",
  RESOLVIENDO_DEUDA: "RESOLVIENDO_DEUDA",
  RESOLVIENDO_QUIEBRA: "RESOLVIENDO_QUIEBRA",
  FINALIZADO: "FINALIZADO"
});

export const TURN_PHASES = Object.freeze({
  AWAITING_ROLL: "AWAITING_ROLL",
  AWAITING_PURCHASE_DECISION: "AWAITING_PURCHASE_DECISION",
  AWAITING_CARD_RESOLUTION: "AWAITING_CARD_RESOLUTION",
  AWAITING_JAIL_DECISION: "AWAITING_JAIL_DECISION",
  AWAITING_TAX_DECISION: "AWAITING_TAX_DECISION",
  AWAITING_RENT_CLAIM: "AWAITING_RENT_CLAIM",
  AWAITING_DEBT_RESOLUTION: "AWAITING_DEBT_RESOLUTION",
  AWAITING_TURN_END: "AWAITING_TURN_END",
  AWAITING_AUCTION: "AWAITING_AUCTION",
  COMPLETED: "COMPLETED"
});

export const SPACE_TYPES = Object.freeze({
  GO: "SALIDA",
  PROPERTY: "PROPIEDAD",
  RAILROAD: "FERROCARRIL",
  UTILITY: "SERVICIO_PUBLICO",
  TAX: "IMPUESTO",
  CHANCE: "CASUALIDAD",
  COMMUNITY_CHEST: "ARCA_COMUNAL",
  JAIL: "CARCEL_VISITA",
  GO_TO_JAIL: "VAYASE_A_LA_CARCEL",
  FREE_PARKING: "PARADA_LIBRE"
});

export const PROPERTY_KINDS = Object.freeze({
  STREET: "SOLAR",
  RAILROAD: "FERROCARRIL",
  UTILITY: "SERVICIO_PUBLICO"
});

export const CARD_DECKS = Object.freeze({
  CHANCE: "CASUALIDAD",
  COMMUNITY_CHEST: "ARCA_COMUNAL"
});

export const CARD_EFFECTS = Object.freeze({
  RECEIVE_MONEY: "RECIBIR_DINERO",
  PAY_BANK: "PAGAR_DINERO",
  PAY_EACH_PLAYER: "PAGAR_A_CADA_JUGADOR",
  RECEIVE_FROM_EACH_PLAYER: "RECIBIR_DE_CADA_JUGADOR",
  MOVE_TO: "MOVER_A",
  MOVE_TO_NEAREST_RAILROAD: "MOVER_A_FERROCARRIL_MAS_CERCANO",
  MOVE_TO_NEAREST_UTILITY: "MOVER_A_SERVICIO_MAS_CERCANO",
  MOVE_BACK: "RETROCEDER",
  GO_TO_JAIL: "IR_A_CARCEL",
  GET_OUT_OF_JAIL: "SALIR_LIBRE_CARCEL",
  REPAIRS: "REPARACIONES"
});

export const CREDITOR_TYPES = Object.freeze({
  BANK: "BANCO",
  PLAYER: "JUGADOR"
});

export const AUCTION_KINDS = Object.freeze({
  PROPERTY: "PROPIEDAD",
  HOUSE: "CASA",
  HOTEL: "HOTEL"
});

export const STARTING_CASH = 1500;
export const BANK_HOUSE_COUNT = 32;
export const BANK_HOTEL_COUNT = 12;
export const GO_SALARY = 200;
export const JAIL_FINE = 50;
export const DEFAULT_INCOME_TAX = 200;
export const DEFAULT_INCOME_TAX_RATE = 0.1;
export const LUXURY_TAX = 100;
export const MAX_CONSECUTIVE_DOUBLES = 3;
export const MAX_JAIL_ATTEMPTS = 3;

export const DEFAULT_ENGINE_OPTIONS = Object.freeze({
  requireRentClaim: false,
  randomizeStartingPlayer: false,
  timedModeDealsInitialProperties: true
});
