/** Static board layout used for store / lobby previews (no live game state). */
export const PREVIEW_BOARD_SPACES = [
  { index: 0, id: "go", name: "Salida", type: "SALIDA" },
  { index: 1, id: "mediterranean", name: "La Paz", shortName: "LPZ", type: "PROPIEDAD", colorGroup: "brown", price: 60 },
  { index: 2, id: "cc1", name: "Arca", type: "ARCA_COMUNAL" },
  { index: 3, id: "baltic", name: "Sucre", shortName: "Sucre", type: "PROPIEDAD", colorGroup: "brown", price: 60 },
  { index: 4, id: "tax1", name: "Impuesto", type: "IMPUESTO" },
  { index: 5, id: "rr1", name: "Tren Maya", type: "FERROCARRIL", price: 200 },
  { index: 6, id: "oriental", name: "Quito", shortName: "Quito", type: "PROPIEDAD", colorGroup: "light_blue", price: 100 },
  { index: 7, id: "chance1", name: "Casualidad", type: "CASUALIDAD" },
  { index: 8, id: "vermont", name: "Cuenca", type: "PROPIEDAD", colorGroup: "light_blue", price: 100 },
  { index: 9, id: "connecticut", name: "Guayaquil", shortName: "GYE", type: "PROPIEDAD", colorGroup: "light_blue", price: 120 },
  { index: 10, id: "jail", name: "Carcel", type: "CARCEL_VISITA" },
  { index: 11, id: "stcharles", name: "Arequipa", shortName: "AQP", type: "PROPIEDAD", colorGroup: "pink", price: 140 },
  { index: 12, id: "electric", name: "Red Andina", type: "SERVICIO_PUBLICO", price: 150 },
  { index: 13, id: "states", name: "Cusco", type: "PROPIEDAD", colorGroup: "pink", price: 140 },
  { index: 14, id: "virginia", name: "Lima", type: "PROPIEDAD", colorGroup: "pink", price: 160 },
  { index: 15, id: "rr2", name: "Tren Pacífico", type: "FERROCARRIL", price: 200 },
  { index: 16, id: "stjames", name: "Valparaiso", shortName: "Valpo", type: "PROPIEDAD", colorGroup: "orange", price: 180 },
  { index: 17, id: "cc2", name: "Arca", type: "ARCA_COMUNAL" },
  { index: 18, id: "tennessee", name: "Concepcion", shortName: "CCP", type: "PROPIEDAD", colorGroup: "orange", price: 180 },
  { index: 19, id: "newyork", name: "Santiago", shortName: "STGO", type: "PROPIEDAD", colorGroup: "orange", price: 200 },
  { index: 20, id: "free", name: "Libre", type: "PARADA_LIBRE" },
  { index: 21, id: "kentucky", name: "Rosario", shortName: "ROS", type: "PROPIEDAD", colorGroup: "red", price: 220 },
  { index: 22, id: "chance2", name: "Casualidad", type: "CASUALIDAD" },
  { index: 23, id: "indiana", name: "Cordoba", shortName: "CBA", type: "PROPIEDAD", colorGroup: "red", price: 220 },
  { index: 24, id: "illinois", name: "Buenos Aires", shortName: "BSAS", type: "PROPIEDAD", colorGroup: "red", price: 240 },
  { index: 25, id: "rr3", name: "Tren Pampa", type: "FERROCARRIL", price: 200 },
  { index: 26, id: "atlantic", name: "Cali", shortName: "Cali", type: "PROPIEDAD", colorGroup: "yellow", price: 260 },
  { index: 27, id: "ventnor", name: "Medellin", shortName: "MDE", type: "PROPIEDAD", colorGroup: "yellow", price: 260 },
  { index: 28, id: "water", name: "Aguas Caribe", type: "SERVICIO_PUBLICO", price: 150 },
  { index: 29, id: "marvin", name: "Bogota", shortName: "BOG", type: "PROPIEDAD", colorGroup: "yellow", price: 280 },
  { index: 30, id: "gotojail", name: "Ve a carcel", type: "VAYASE_A_LA_CARCEL" },
  { index: 31, id: "pacific", name: "Brasilia", shortName: "BSB", type: "PROPIEDAD", colorGroup: "green", price: 300 },
  { index: 32, id: "northcarolina", name: "Rio de Janeiro", shortName: "RIO", type: "PROPIEDAD", colorGroup: "green", price: 300 },
  { index: 33, id: "cc3", name: "Arca", type: "ARCA_COMUNAL" },
  { index: 34, id: "pennsylvania", name: "Sao Paulo", shortName: "SP", type: "PROPIEDAD", colorGroup: "green", price: 320 },
  { index: 35, id: "rr4", name: "Tren Austral", type: "FERROCARRIL", price: 200 },
  { index: 36, id: "chance3", name: "Casualidad", type: "CASUALIDAD" },
  { index: 37, id: "park", name: "Guadalajara", shortName: "GDL", type: "PROPIEDAD", colorGroup: "dark_blue", price: 350 },
  { index: 38, id: "tax2", name: "Lujo", type: "IMPUESTO" },
  { index: 39, id: "boardwalk", name: "Ciudad de Mexico", shortName: "CDMX", type: "PROPIEDAD", colorGroup: "dark_blue", price: 400 }
];
